### PR TITLE
Created SparkSteel8 page and modified gc.md to apply recent updates to the faction

### PR DESCRIPTION
**Pull request by SparkSteel8**
…pdates

### CODE REVIEW

**Comment by CC52-dev** [comment]
Yes ik that, its not done yet so, I dont really wantt it public

**Comment by hamhimstudio** [comment]
what xylium said + markdown files should be simplecase, not really a rule or anything but that's how its for other pages, consistency is key

**Comment by hamhimstudio** [comment]
also what you did with the title and description is *not* funny...

**Comment by hamhimstudio** [comment]
image also seems to have expired, not a fault on your end however, rather on discord's end.

**Pull request closed without merging**
